# Generated by Django 4.1.5 on 2023-01-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_waifu_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waifu',
            name='value',
        ),
    ]
