# Generated by Django 4.1.5 on 2023-01-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_remove_waifu_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default='Deity'),
            preserve_default=False,
        ),
    ]
