# Generated by Django 4.1.5 on 2023-01-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waifu',
            old_name='rank',
            new_name='rarity',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='user',
            name='money',
        ),
    ]
