# Generated by Django 4.1.5 on 2023-01-21 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.IntegerField()),
                ('money', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Waifu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('source', models.TextField()),
                ('post_count', models.IntegerField(default=0)),
                ('best_safe_post_id', models.IntegerField(default=0)),
                ('best_safe_post_score', models.IntegerField(default=0)),
                ('best_safe_post_image', models.TextField(default=None)),
                ('best_unsafe_post_id', models.IntegerField(default=0)),
                ('best_unsafe_post_score', models.IntegerField(default=0)),
                ('best_unsafe_post_image', models.TextField(default=None)),
                ('value', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.user')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.user')),
                ('waifu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.waifu')),
            ],
        ),
    ]
