# Generated by Django 4.1.5 on 2023-01-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waifu',
            name='best_safe_post_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='waifu',
            name='best_safe_post_image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='waifu',
            name='best_safe_post_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='waifu',
            name='best_unsafe_post_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='waifu',
            name='best_unsafe_post_image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='waifu',
            name='best_unsafe_post_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='waifu',
            name='post_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='waifu',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
